export const PUBLISHED_WEBSITES = [
  {
    href: "https://risingelectronics.com",
    thumbnail: "/assets/websites/published/risingelectronics_com_frontpage.png",
    tagEn: "Commerce",
    tagZh: "商業",
    titleEn: "Rising Electronics",
    titleZh: "穗升國際有限公司",
    domain: "risingelectronics.com",
    descriptionEn: "An electronics manufacturer based in Hong Kong.",
    descriptionZh: "一家位於香港的電子產品製造商。",
    category: "published" as const,
  }
];

export const TEMPLATES = [
  {
    href: "/demos/event_template/",
    thumbnail: "/assets/websites/templates/event_template_website_frontpage.png",
    tagEn: "Events",
    tagZh: "活動",
    titleEn: "Event Template",
    titleZh: "活動模板",
    descriptionEn: "A flexible template for events and occasions.",
    descriptionZh: "一個適用於活動和場合的靈活模板。",
    category: "templates" as const,
  },
  {
    href: "/demos/dentist_template/",
    thumbnail: "/assets/websites/templates/dentist_template_website_frontpage.png",
    tagEn: "Medical",
    tagZh: "醫療",
    titleEn: "Hong Kong Dental Clinic",
    titleZh: "香港牙科診所",
    descriptionEn: "A bilingual dental clinic template for Hong Kong.",
    descriptionZh: "一個適合香港的雙語牙科診所模板。",
    category: "templates" as const,
  },
  {
    href: "/demos/gym_template/",
    thumbnail: "/assets/websites/templates/gym_template_website_frontpage.png",
    tagEn: "Fitness",
    tagZh: "健身",
    titleEn: "Hong Kong Functional Fitness",
    titleZh: "香港功能性健身",
    descriptionEn: "A bilingual gym template with EN/ZH switching.",
    descriptionZh: "一個帶有中英文切換的雙語健身模板。",
    category: "templates" as const,
  },
  {
    href: "/demos/hair_salon_template/",
    thumbnail: "/assets/websites/templates/hair_salon_template_website_frontpage.png",
    tagEn: "Beauty",
    tagZh: "美容",
    titleEn: "Hong Kong Hair Salon",
    titleZh: "香港髮廊時尚",
    descriptionEn: "A bilingual hair salon template with EN/ZH switching.",
    descriptionZh: "一個帶有中英文切換的雙語髮廊模板。",
    category: "templates" as const,
  },
  {
    href: "/demos/barefoot_shoe_template/",
    thumbnail: "/assets/websites/templates/barefoot_shoe_template_website_frontpage.png",
    tagEn: "Footwear",
    tagZh: "鞋履",
    titleEn: "Hong Kong Barefoot Shoes",
    titleZh: "香港赤足鞋",
    descriptionEn: "A bilingual barefoot shoe store template with EN/ZH switching.",
    descriptionZh: "一個帶有中英文切換的雙語赤足鞋店模板。",
    category: "templates" as const,
  },
  {
    href: "/demos/phone_repair_template/",
    thumbnail: "/assets/websites/templates/phone_repair_template_website_frontpage.png",
    tagEn: "Tech Repair",
    tagZh: "科技維修",
    titleEn: "FIXHUB Phone Repair",
    titleZh: "FIXHUB 手機維修",
    descriptionEn: "A bilingual phone repair template with tech aesthetic.",
    descriptionZh: "一個帶有科技感雙語風格的手機維修模板。",
    category: "templates" as const,
  }
];

export const INITIAL_PROJECTS = [
  {
    repo: 'jobsdb-scraper',
    icon: 'https://hk.jobsdb.com/static/shared-web/favicon-4e1897dfd0901e8a3bf7e604d3a90636.ico',
    name: 'JobsDB Scraper',
    description: 'A tool to scrape job listings from JobsDB.',
    url: '#',
  },
  {
    repo: 'whatstheweatherlike',
    icon: 'https://ssl.gstatic.com/onebox/weather/64/sunny.png',
    name: "What's the weather like",
    description: 'A simple weather application.',
    url: '#',
  },
  {
    repo: 'chatroom',
    icon: '/assets/live-chat.png',
    name: 'Chatroom',
    description: 'A real-time chat application.',
    url: '#',
  },
];
